name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: cd app && npm ci

      - name: Run prettier & eslint
        run: cd app && npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_AUTH_TOKEN: ${{ secrets.DATABASE_AUTH_TOKEN }}
      DATABASE_REPLICA: ${{ secrets.DATABASE_REPLICA }}
      DATABASE_SYNC: ${{ secrets.DATABSE_SYNC }}
      APP_ENV: ${{ secrets.APP_ENV }}
    outputs:
      APP_VERSION: ${{ steps.infoOutput.outputs.APP_VERSION }}
      COMMIT_SHA: ${{ steps.infoOutput.outputs.COMMIT_SHA }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: cd app && npm ci

      - name: Build app
        run: cd app && npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          retention-days: 3
          path: |
            app/build
            app/ecosystem.config.cjs
            app/svelte.config.js
            app/package.json
            app/package-lock.json
            app/node_modules
            app/script
            app/.svelte-kit

      - name: Output info
        id: infoOutput
        run: |
          echo "APP_VERSION=$VERSION" >> "$GITHUB_OUTPUT"
          echo "COMMIT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      APP_VERSION: ${{ steps.infoOutput.outputs.APP_VERSION }}
      COMMIT_SHA: ${{ steps.infoOutput.outputs.COMMIT_SHA }}
    environment: production

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: app

      - name: List downloaded files
        run: ls -R app

      - name: Add deployment SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          printf "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      - name: Generate .env.production
        run: |
          cd app
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.production
          # echo "DATABASE_AUTH_TOKEN=${{ secrets.DATABASE_AUTH_TOKEN }}" >> .env.production
          # echo "DATABASE_REPLICA=${{ secrets.DATABASE_REPLICA }}" >> .env.production
          # echo "DATABASE_SYNC=${{ secrets.DATABSE_SYNC }}" >> .env.production
          echo "APP_ENV=${{ secrets.APP_ENV }}" >> .env.production
          echo "APP_VERSION=$APP_VERSION" >> .env.production
          echo "BUILD_DATE=$(date -u +"%Y-%m-%d")" >> .env.production
          echo "COMMIT_SHA=$COMMIT_SHA" >> .env.production
          ls -l .env.production

      - name: Upload build to server
        run: rsync -az --progress -e ssh ./app/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/github_actions/nyx/app/

      - name: Restart server
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ~/github_actions/nyx/app && source ~/.nvm/nvm.sh && pm2 start ecosystem.config.cjs && pm2 show nyx"
