name: Continuous Integration

on:
  push:
    branches-ignore:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate .env.test file
        run: |
          pwd
          echo "DATABASE_URL=${{ vars.DATABASE_URL }}" >> .env.test
          echo "ORIGIN=${{ vars.ORIGIN }}" >> .env.test
          echo "APP_ENV=${{ vars.APP_ENV }}" >> .env.test
          ls -l .env.test

      - name: Build app
        run: npm run build:test

      - name: Database setup
        run: |
          pwd
          npm run db:migrate:test

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build-testE2E
          retention-days: 3
          path: |
            build
            ecosystem.config.cjs
            svelte.config.js
            package.json
            package-lock.json
            node_modules
            script
            .svelte-kit
            *.db

  test:
    runs-on: ubuntu-latest
    environment: test
    env:
      DATABASE_URL: ${{ vars.DATABASE_URL }}
      ORIGIN: ${{ vars.ORIGIN }}
      APP_ENV: ${{ vars.APP_ENV }}
    defaults:
      run:
        working-directory: app

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: app

      - name: Install dependencies
        run: npm ci

      # - name: Generate .env.test file
      #   run: |
      #     ls
      #     pwd
      #     echo "DATABASE_URL=${{ vars.DATABASE_URL }}" >> .env.test
      #     echo "ORIGIN=${{ vars.ORIGIN }}" >> .env.test
      #     echo "APP_ENV=${{ vars.APP_ENV }}" >> .env.test
      #     ls -l .env.test

      - name: Start preview server
        run: |
          npm run preview:test &

      - name: Wait for app
        run: npx wait-on http://localhost:4173

      - name: Run Playwright
        run: |
          npx playwright install --with-deps
          npx playwright test
